server:
  port: 8081

spring:
  application:
    name: order-service

  cloud:
    stream:
      # ???(Binding): ??? RabbitMQ ???? ??
      # ?? ??? Naming: "????-out-???" (?? ?? ?? ??)
      bindings:
        order-created-out-0:
          destination: order-events-topic
          content-type: application/json

      rabbit:
        bindings:
          order-created-out-0:
            producer:
              transacted: true # ???? (??? ??? ? ??? ? ???? ??)